function [low_gl_fit, high_gl_fit, low_gl_xdata, low_gl_ydata, high_gl_xdata, high_gl_ydata, gof] = gl_Gaylard2_fit(time_series, low_gl_glucose_data, high_gl_glucose_data)
%CREATEFIT(TIME_SERIES,LOW_GL_GLUCOSE_DATA)
%  Create a fit.
%
%  Data for 'LowGL Gaylard 2 fit' fit:
%      X Input: time_series
%      Y Output: low_gl_glucose_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2023 09:36:24


%% Fit: 'LowGL Gaylard 2 fit'.
[xData, yData] = prepareCurveData( time_series, low_gl_glucose_data );
low_gl_xdata = xData;
low_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'a*x^(b*x^(-c))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.MaxIter = 4000;
opts.StartPoint = [0.254790156597005 0.224040030824219 0.968649330231094];

% Fit model to data.
[low_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'LowGL Gaylard 2 fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'low_gl_glucose_data vs. time_series', 'LowGL Gaylard 2 fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'time_series', 'Interpreter', 'none' );
% ylabel( 'low_gl_glucose_data', 'Interpreter', 'none' );
% grid on

%% Fit: 'HighGL Gaylard 2 fit'.
[xData, yData] = prepareCurveData( time_series, high_gl_glucose_data );

high_gl_xdata = xData;
high_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'a*x^(b*x^(-c))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.MaxIter = 4000;
opts.StartPoint = [0.01 1 0.341124607049109];

% Fit model to data.
[high_gl_fit, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'HighGL Gaylard 2 fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'high_gl_glucose_data vs. time_series', 'HighGL Gaylard 2 fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
% xlabel( 'time_series', 'Interpreter', 'none' );
% ylabel( 'high_gl_glucose_data', 'Interpreter', 'none' );
% grid on

