function [low_gl_fit, high_gl_fit, low_gl_xdata, low_gl_ydata, high_gl_xdata, high_gl_ydata, gof] = gl_Gaylard_fit(time_series, low_gl_glucose_data, high_gl_glucose_data)
%CREATEFIT(TIME_SERIES,HIGH_GL_GLUCOSE_DATA)
%  Create a fit.
%
%  Data for 'High GL Gaylard fit' fit:
%      X Input: time_series
%      Y Output: high_gl_glucose_data
%  Output:
%      high_gl_fit : a fit object representing the fit.
%      low_gl_fit : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2023 09:21:30


%% Fit: 'High GL Gaylard fit'.
[xData, yData] = prepareCurveData( time_series, high_gl_glucose_data );
high_gl_xdata = xData;
high_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'x/(1+a*x+b*sqrt(x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.695140499551737 0.0679927684700106];

% Fit model to data.
[high_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'High GL Gaylard fit' );
%h = plot( fitresult, xData, yData );
%legend( h, 'high_gl_glucose_data vs. time_series', 'High GL Gaylard fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'high_gl_glucose_data', 'Interpreter', 'none' );
%grid on

%% Fit: 'LowGL Gaylard fit'.
[xData, yData] = prepareCurveData( time_series, low_gl_glucose_data );

low_gl_xData = xData;
low_gl_yData = yData;
% Set up fittype and options.
ft = fittype( 'x/(1+a*x+b*sqrt(x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.254790156597005 0.224040030824219];

% Fit model to data.
[low_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'LowGL Gaylard fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'low_gl_glucose_data vs. time_series', 'LowGL Gaylard fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'time_series', 'Interpreter', 'none' );
% ylabel( 'low_gl_glucose_data', 'Interpreter', 'none' );
% grid on

