function [low_gl_fit, high_gl_fit, low_gl_xdata, low_gl_ydata, high_gl_xdata, high_gl_ydata, gof] = gl_gaussian_fit(time_series, low_gl_glucose_data, high_gl_glucose_data)
%CREATEFIT(TIME_SERIES,LOW_GL_GLUCOSE_DATA)
%  Create a fit.
%
%  Data for 'Low GL Gaussian fit' fit:
%      X Input: time_series
%      Y Output: low_gl_glucose_data
%  Output:
%      low_gl_fit : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2023 03:15:23


%% Fit: 'Low GL Gaussian fit'.
[xData, yData] = prepareCurveData( time_series, low_gl_glucose_data );
low_gl_xdata = xData;
low_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.StartPoint = [97.9 -0.151975865897276 0.765662513588576 88.1409346954886 1.62107590290427 0.891915163128111];

% Fit model to data.
[low_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'Low GL Gaussian fit' );
%h = plot( low_gl_fit, xData, yData );
%legend( h, 'low_gl_glucose_data vs. time_series', 'Low GL Gaussian fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'low_gl_glucose_data', 'Interpreter', 'none' );
%grid on

%% Fit: 'High GL Gaussian fit'.
[xData, yData] = prepareCurveData( time_series, high_gl_glucose_data );
high_gl_xdata = xData;
high_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.StartPoint = [110.2 -0.506586219657586 0.672738685705156 93.2950098748857 1.62107590290427 1.01323897377588];

% Fit model to data.
[high_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'High GL Gaussian fit' );
%h = plot( high_gl_fit, xData, yData );
%legend( h, 'high_gl_glucose_data vs. time_series', 'High GL Gaussian fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'high_gl_glucose_data', 'Interpreter', 'none' );
%grid on
