function [low_gl_fit, high_gl_fit, low_gl_xdata, low_gl_ydata, high_gl_xdata, high_gl_ydata, gof] = gl_sum_of_sines_fit(time_series, low_gl_glucose_data, high_gl_glucose_data)
%CREATEFIT(TIME_SERIES,LOW_GL_GLUCOSE_DATA)
%  Create a fit.
%
%  Data for 'Low GL Sum of Sines fit' fit:
%      X Input: time_series
%      Y Output: low_gl_glucose_data
%  Output:
%      low_gl_fit : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2023 03:13:07


%% Fit: 'Low GL Sum of Sines fit'.
[xData, yData] = prepareCurveData( time_series, low_gl_glucose_data );
low_gl_xdata = xData;
low_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.Normalize = 'on';
opts.StartPoint = [148.65078548906 1.10741008415158 1.30256907789603 70.1722750142885 2.21482016830315 -2.09878479728153];

% Fit model to data.
[low_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'Low GL Sum of Sines fit' );
%h = plot( low_gl_fit, xData, yData );
%legend( h, 'low_gl_glucose_data vs. time_series', 'Low GL Sum of Sines fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'low_gl_glucose_data', 'Interpreter', 'none' );
%grid on

%% Fit: 'High GL Sum of Sines fit'.
[xData, yData] = prepareCurveData( time_series, high_gl_glucose_data );
high_gl_xdata = xData;
high_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.Normalize = 'on';
opts.StartPoint = [160.008853684246 1.10741008415158 1.28896502115402 72.520479336943 2.21482016830315 -2.17213888722962];

% Fit model to data.
[high_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'High GL Sum of Sines fit' );
%h = plot( high_gl_fit, xData, yData );
%legend( h, 'high_gl_glucose_data vs. time_series', 'High GL Sum of Sines fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'high_gl_glucose_data', 'Interpreter', 'none' );
%grid on
