function [low_gl_fit, high_gl_fit, low_gl_xdata, low_gl_ydata, high_gl_xdata, high_gl_ydata, gof] = gl_fourier_fit(time_series, low_gl_glucose_data, high_gl_glucose_data)
%CREATEFIT(TIME_SERIES,LOW_GL_GLUCOSE_DATA)
%  Create a fit.
%
%  Data for 'Low GL Fourier fit' fit:
%      X Input: time_series
%      Y Output: low_gl_glucose_data
%  Output:
%      low_gl_fit : a fit object representing the fit.
%      high_gl_fit : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2023 03:12:09


%% Fit: 'Low GL Fourier fit'.
[xData, yData] = prepareCurveData( time_series, low_gl_glucose_data );
low_gl_xdata = xData;
low_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'fourier2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0 0 0 0 0 1.10741008415158];

% Fit model to data.
[low_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'Low GL Fourier fit' );
%h = plot( low_gl_fit, xData, yData );
%legend( h, 'low_gl_glucose_data vs. time_series', 'Low GL Fourier fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'low_gl_glucose_data', 'Interpreter', 'none' );
%grid on

%% Fit: 'High Gl Fourier fit'.
[xData, yData] = prepareCurveData( time_series, high_gl_glucose_data );
high_gl_xdata = xData;
high_gl_ydata = yData;
% Set up fittype and options.
ft = fittype( 'fourier2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0 0 0 0 0 1.10741008415158];

% Fit model to data.
[high_gl_fit, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'High Gl Fourier fit' );
%h = plot( high_gl_fit, xData, yData );
%legend( h, 'high_gl_glucose_data vs. time_series', 'High Gl Fourier fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
%% Label axes
%xlabel( 'time_series', 'Interpreter', 'none' );
%ylabel( 'high_gl_glucose_data', 'Interpreter', 'none' );
%grid on
