name: Update Changelog
on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
    paths-ignore:
      - 'CHANGELOG.md'
    types:
      - closed
  workflow_dispatch:
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: !contains(github.event.pull_request.labels.*.name, 'update-changelog')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Changelog using github-changelog-generator
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }}
      - name: setup_user
        uses: fregante/setup-git-user@v2
      - name: create pr
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        with:
          labels: update-changelog
          assignees: ${{ github.actor }}
          title: Updated CHANGELOG
          branch: update-changelog
     
