name: Update Changelog
on:
  pull_request:
    branches: 
      - 'main'
    types:
      - closed
  workflow_dispatch:
permissions: write-all
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Changelog using github-changelog-generator
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.ADMIN_TOKEN }}
      - name: setup_user
        run: |
          git config --global user.email jono.faller@gmail.com
          git config --global user.name JonoLF
      - name: push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          git pull
          git add --all
          git commit -m "Updated CHANGELOG"
          git push 
     
