name: Update Changelog
on:
  pull_request:
    branches: 
      - 'main'
    types:
      - closed
  workflow_dispatch:
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'update-changelog') == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Changelog using github-changelog-generator
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }}
      - name: setup_user
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
      - name: force push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          git add --all
          git commit -m "Updated CHANGELOG"
          git push
     
