name: Update Changelog
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Changelog using github-changelog-generator
        uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }}
      - name: setup_user
        uses: fregante/setup-git-user@v2
      - name: create pr
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          labels: documentation
          assignees: ${{ github.actor }}
          title: Updated CHANGELOG
          branch: update-changelog
      - name: merge pr
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          if [ "$(git diff --cached main HEAD~1 | grep -F '^CHANGELOG.md:') -eq '' ]; then
            echo "Changelog has not been updated. Skipping merge."
            exit 0
          fi
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --admin
