name: Merge Changelog
on:
  pull_request_target:
    types: 
      - labeled
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    if: event.label.name == 'update-changelog'
    steps:
    - name: merge-pr
      uses: nbrugger-tgm/merge-pr-action@v0.2.2
      with:
        token: ${{ secrets.ADMIN_TOKEN }}
        method: merge
            
            

