name: Merge Changelog
on:
  pull_request_target:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - synchronize
jobs:
  merge:
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request.labels[0].name == 'update-changelog'
    steps:
    - name: merge-pr
      env:
        GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        PR: ${{ github.event.pull_request.html_url }}
      run: |
        gh pr merge $PR --admin --merge
      
            
            

